CREATE SCHEMA IF NOT EXISTS qdm;
CREATE SCHEMA IF NOT EXISTS value_set;
CREATE SCHEMA IF NOT EXISTS cql;
CREATE SCHEMA IF NOT EXISTS ecqm;
CREATE SCHEMA IF NOT EXISTS vte;
CREATE SCHEMA IF NOT EXISTS global;
CREATE SCHEMA IF NOT EXISTS tjc;
CREATE SCHEMA IF NOT EXISTS data_elements;

